### ISSUE TITLE
Credit to the original author?

### ISSUE THREAD

**Issue by prdoyle** [AdoptOpenJDK/bumblebench#6]
Might I humbly suggest it would be appropriate to give some kind of credit/recognition to the author of Bumblebench (namely me) somewhere in the code or docs?

**Comment by tellison** [comment]
Hi Patrick.

I realise you wrote "author", but just checking that you are referring to _authorship_, and not _ownership_ here.  I need to be clear that there is no dispute that all the code is received under ALv2 from the correct owner(s).

Please take a look at [our contribution guide](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/CONTRIBUTING.md#source-file-headers).  As a policy we don't attribute copyright or authorship within the project for the reasons given within the contribution guide.  We'd be happy to have further discussion on this topic if you are interested, the best place for that is in [the TSC issue tracker](https://github.com/AdoptOpenJDK/TSC/issues).

We're delighted to see the Bumblebench code arrive here at AdoptOpenJDK - thanks to you and everyone who has contributed to creating it and getting it out for people to use.

**Comment by prdoyle** [comment]
Hi Tim,

Sorry to alarm you -- I'm not trying to assert any kind of copyright or other IP "ownership" of the code.  I wrote it as an employee of IBM and I'm happy for it to be considered a work for hire, and therefore owned by IBM.  Just perhaps looking for some small shout-out on the README.md or similar, since the git history has no record of the fact that most of the files in this repository are the original, unmodified files written by Nick Korovaiko and myself about three years ago.

**Comment by karianna** [comment]
~~@prdoyle I think that's reasonable, I'm happy to assign original author credit in that case.  Since new features will be added are you and @tellison happy if I just put a blanket notice on the README.md of the project saying something like "Original version authored by Peter Doyle and Nick Korovaiko at IBM in 2015. Donated by IBM to the AdoptOpenJDK project in 2018"?~~

**Comment by karianna** [comment]
Hi @prdoyle , on further thought it’s going to be impossible for AdoptOpenJDK to credit each developer or contributor in a fair manner across all of the code (getting to 100K+ LOC now!) that has been donated to AdoptOpenJDK by their various legal owners. It’s why we’ve gone for the ‘no author’ policy (not to mention our philosophy of shared code ownership).  Apologies for leading you down the wrong path earlier today.

**Comment by prdoyle** [comment]
You are conflating authorship with ownership.  I'm not asking you to credit each developer or contributor in a fair manner across all of the code.  I'm asking you to credit myself and Nick for this code base.  A "no author" policy is a pleasant-sounding euphemism for plagiarism.

Probably 60% of this repo is code I wrote, completely unchanged, and a further 20% is code Nick wrote.  If this discussion ends up being the only acknowledgement we get, so be it.

**Comment by gdams** [comment]
Hi @prdoyle I understand that you may feel dissapointed about this code being open sourced by IBM and no accreditation being given to you. As I'm sure you were aware during your time working at IBM, any code produced is actually IBM's property unless otherwise stated. Whilst I appreciate that you clearly spent a huge amount of time writing this source code, IBM has agreed to donate this code to AdoptOpenJDK and as part of this process any commit history is erased. I myself have written many thousands of lines of code for this project and have also then had my source code donated to AdoptOpenJDK with no direct credit being given to me.

I would hope that you feel proud that such a large codebase that you wrote is now in the open and available for public use. There are many thousands of developers that contribute to similar projects each day and your work on this project has hopefuly made the Java eco-system better for everyone.

I would be very happy to deal with any further concerns that you may have but the way I personally view this is that IBM owned this source code and as a company made the decision to donate it to AdoptOpenJDK. IBM along with many other companies involved with the project receive the appropriate accreditation [here](https://adoptopenjdk.net/sponsors.html#tier-1-sponsors).

**Comment by prdoyle** [comment]
@gdams I agree with literally every word in your comment, with one exception: I am delighted that the code has been open sourced, full stop.

I'm sensing, however, that you may have glossed over the distinction I am drawing between ownership (a matter of intellectual property) and authorship (a matter of intellectual honesty).  I don't care about staking a claim, nor about asserting rights.  I care about getting credit for what I created.

I believe a "no author" policy that refuses even to acknowledge people's contributions is lazy, unfair, and unethical.  In contrast, I'm fully in favour of a "no owner" policy that requires people to give up their right to restrict the freedom of those using the code.

In any case, my disappointment is minor.  I'm delighted this has been open sourced, and hope I'll be able to contribute in the future.
